# Generated by Django 3.0 on 2019-12-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageb', models.ImageField(upload_to='images/')),
                ('body', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=25)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
